# Generated by Django 3.0 on 2022-08-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='email',
        ),
    ]
